Vagrant.configure("2") do |config|

    config.vm.box = 'bento/centos-7.3'
    config.vm.provision "shell",  :path => "provision.sh"
    config.vm.provision "shell",  :path => "target/scripts/migration.sh"
    config.vm.provision "shell",  :path => "target/scripts/server-start.sh"
    config.vm.provision "shell",  :path => "target/scripts/run-it.sh"
    config.vm.provision "shell",  :path => "target/scripts/server-stop.sh"

    config.vm.define :wasabiosit do |dev|
        dev.vm.hostname = "wasabi.os.it"
        dev.vm.boot_timeout = 3000

        dev.vm.provider "virtualbox" do |v|
            v.name = "wasabi.os.it.vbox"
            v.memory = 8192
            v.cpus = 8
            v.customize ["modifyvm", :id, "--cableconnected1", "on"]
        end
    end
end
