#!/bin/sh
###############################################################################
# Copyright 2016 Intuit
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

HOME_DIR=${application.home}
JMX_PORT=${application.jmx.port}
DEBUG_PORT=${application.debug.port}
LOG_DIR=${log.dir}
MAIN=${application.main}
DAEMON=\${WASABI_DAEMON:-${application.daemon.enable}}
CONSOLE_LOG=\${LOG_DIR}/${application.name}-console.log
CLASSPATH=\${HOME_DIR}/conf:\${HOME_DIR}/lib/${application.name}-all.jar
HEAP_SIZE=${application.heapsize}

JAVA_OPTIONS="
  -Xms\${HEAP_SIZE}\
  -Xmx\${HEAP_SIZE}\
  -server\
  ${application.instrument}\
  ${application.monitor}\
  -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=\${LOG_DIR}/java_$$.hprof\
  -XX:+UseConcMarkSweepGC -XX:+UseParNewGC\
  -verbose:gc -Xloggc:\${LOG_DIR}/gc.log\
  -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime\
  -XX:+PrintGCApplicationConcurrentTime -XX:+PrintTenuringDistribution\
  -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=\${DEBUG_PORT}\
  -Djava.rmi.server.hostname=`hostname`\
  -Dcom.sun.management.jmxremote=true\
  -Dcom.sun.management.jmxremote.port=\${JMX_PORT}\
  -Dcom.sun.management.jmxremote.ssl=false\
  -Dcom.sun.management.jmxremote.authenticate=false\
  -Dlogback.configurationFile=\${HOME_DIR}/conf/logback.xml\
  -Djava.util.logging.config.file=\${HOME_DIR}/conf/logging.properties\
  ${WASABI_CONFIGURATION}"

# if JAVA_HOME is not set, set it based on OS
if [ "$JAVA_HOME" = "" ]; then
  if [ -f /usr/libexec/java_home ]; then
    # OSX
    export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
  elif [ -d /usr/java/latest ]; then
    # Linux
    export JAVA_HOME=/usr/java/latest  
  else
    echo "Error: JAVA_HOME could not be identified"
    exit 1
  fi
fi

if [ \${DAEMON} = "true" ]; then
  run_as="chpst -u ${application.user}:${application.group}"
fi

exec $run_as \${JAVA_HOME}/bin/java \${JAVA_OPTIONS} -cp \${CLASSPATH} \${MAIN} 1>>\${CONSOLE_LOG} 2>&1
